package loginandregister;


import java.sql.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rucha
 */
public class adminmanagement extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public adminmanagement() {
        initComponents();
        this.setAlwaysOnTop(false);
        this.setSize(500,450);
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setTitle("Blood Bank Management System");

    }
    public void close()
     {
      WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bill = new javax.swing.JButton();
        bldman = new javax.swing.JButton();
        backwa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(793, 443));
        setPreferredSize(new java.awt.Dimension(793, 443));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(202, 242, 255));
        jPanel2.setLayout(null);

        bill.setBackground(new java.awt.Color(204, 204, 204));
        bill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bill.setText("BILLING");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        jPanel2.add(bill);
        bill.setBounds(280, 80, 223, 31);

        bldman.setBackground(new java.awt.Color(204, 204, 204));
        bldman.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bldman.setText("BLOOD MANAGEMENT");
        bldman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldmanActionPerformed(evt);
            }
        });
        jPanel2.add(bldman);
        bldman.setBounds(280, 170, 223, 33);

        backwa.setBackground(new java.awt.Color(204, 204, 204));
        backwa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backwa.setText("BACK");
        backwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backwaActionPerformed(evt);
            }
        });
        jPanel2.add(backwa);
        backwa.setBounds(280, 260, 223, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandregister/140508100350_1_540x360.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 370);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 810, 370);

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 810, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bldmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldmanActionPerformed
        // TODO add your handling code here:
      close();
      this.dispose();
      bldstorage bld =new bldstorage();
      bld.setVisible(true);
      
    }//GEN-LAST:event_bldmanActionPerformed

    private void backwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwaActionPerformed
        // TODO add your handling code here:
      close();
      this.dispose();
      mainmenu menu =new mainmenu();
      menu.setVisible(true);
    }//GEN-LAST:event_backwaActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
     close();
     this.dispose();
      bill bll =new bill();
      bll.setVisible(true);
    }//GEN-LAST:event_billActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminmanagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backwa;
    private javax.swing.JButton bill;
    private javax.swing.JButton bldman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
