package loginandregister;


//import java.awt.Color;
import java.sql.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class login1 extends javax.swing.JFrame {

    
    public login1() {
        initComponents();
        this.setAlwaysOnTop(false);
        this.setSize(500,450);
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setTitle("Blood Bank Management System");
        
       // this.setLocationRelativeTo(null);//center form in the screen
      //  jPanel1.setFocusable(true);
    }
    public void close()
     {
      WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        uname = new javax.swing.JLabel();
        pword = new javax.swing.JLabel();
        epword = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        ename = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(802, 503));
        setPreferredSize(new java.awt.Dimension(802, 503));
        setResizable(false);
        setSize(new java.awt.Dimension(802, 503));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("LOGIN  FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(586, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 70);

        jPanel2.setBackground(new java.awt.Color(202, 242, 255));
        jPanel2.setLayout(null);

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setText("Username   :");
        jPanel2.add(uname);
        uname.setBounds(127, 78, 130, 22);

        pword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pword.setForeground(new java.awt.Color(255, 255, 255));
        pword.setText("Password   :");
        jPanel2.add(pword);
        pword.setBounds(127, 190, 130, 22);

        epword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(epword);
        epword.setBounds(356, 187, 194, 26);

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setText("LOGIN");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login);
        login.setBounds(350, 340, 79, 25);

        reset.setBackground(new java.awt.Color(204, 204, 204));
        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(610, 340, 79, 25);

        ename.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enameFocusLost(evt);
            }
        });
        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        jPanel2.add(ename);
        ename.setBounds(356, 75, 194, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandregister/background.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 21, 800, 430);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 810, 460);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        
        String name1=ename.getText();
        String password=epword.getText();
        if(name1.contains("admin") && password.contains("123"))
        {    
        
         JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFUL !");
         close();     
         this.dispose();
         mainmenu menu =new mainmenu();
         menu.setVisible(true);
         
        } 
        else
        {
         JOptionPane.showMessageDialog(null,"Enter Correct Username and Password ", "Invalid Login !",JOptionPane.ERROR_MESSAGE);
       
         close();
         this.dispose();
         login1 log =new login1();
         log.setVisible(true);
         log.setLocationRelativeTo(null);
         log.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
         
        /* mainmenu menu =new mainmenu();
         menu.setVisible(true);
         menu.setLocationRelativeTo(null);
         menu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        */
      //this.dispose();
    }//GEN-LAST:event_loginActionPerformed
   
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       ename.setText("");
       epword.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loginMouseClicked

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void enameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enameFocusGained
        // TODO add your handling code here:
   /*     if((ename.getText().equals("Enter Email ID")))
        {
          ename.setText("");
        }
       ename.setForeground(Color.GRAY);*/
    }//GEN-LAST:event_enameFocusGained

    private void enameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enameFocusLost
        // TODO add your handling code here:
      /*  if((ename.getText().equals("")))
        {
           ename.setText("Enter Email ID");
        }
        ename.setForeground(new Color(0,51,51));*/
    }//GEN-LAST:event_enameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ename;
    private javax.swing.JPasswordField epword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JLabel pword;
    private javax.swing.JButton reset;
    private javax.swing.JLabel title;
    private javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
