package loginandregister;

import java.sql.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.regex.*;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rucha
 */
public class receipent_reg extends javax.swing.JFrame {
    PreparedStatement addChPS=null, fetChPS=null, searchChPS=null, modifyChPS=null, deleteChPS=null;
    Connection con=null;
    ResultSet fetChRes=null, searchChRes=null;
    
    public receipent_reg() {
        
         
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setTitle("Blood Bank Management System");
        update.setEnabled(false);
        delete.setEnabled(false);
        this.setAlwaysOnTop(false);
        System.out.println("Set and ready");
    }
     public void close()
     {
      WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        address = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        uage = new javax.swing.JTextField();
        iname = new javax.swing.JLabel();
        icontact = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        uaddress = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        display = new javax.swing.JButton();
        ucontact = new javax.swing.JTextField();
        iage1 = new javax.swing.JLabel();
        client_id = new javax.swing.JLabel();
        uclientid = new javax.swing.JTextField();
        client1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        bldgrp = new javax.swing.JLabel();
        ubldgrps = new javax.swing.JComboBox<>();
        adhar = new javax.swing.JTextField();
        weight1 = new javax.swing.JLabel();
        iadhar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        ulast_name = new javax.swing.JTextField();
        iname2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(809, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(809, 640));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("RECEIPENT REGISTRATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 50);

        jPanel2.setBackground(new java.awt.Color(202, 242, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("FIRST NAME        :");
        jPanel2.add(name);
        name.setBounds(110, 60, 140, 20);

        uname.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unameKeyReleased(evt);
            }
        });
        jPanel2.add(uname);
        uname.setBounds(270, 60, 226, 30);

        register.setBackground(new java.awt.Color(204, 204, 204));
        register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register.setText("Register");
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel2.add(register);
        register.setBounds(10, 490, 89, 35);

        reset.setBackground(new java.awt.Color(204, 204, 204));
        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(580, 490, 79, 35);

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Address     :");
        jPanel2.add(address);
        address.setBounds(130, 180, 96, 17);

        age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("Age             :");
        jPanel2.add(age);
        age.setBounds(130, 360, 96, 17);

        contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setText("Contact No :");
        jPanel2.add(contact);
        contact.setBounds(110, 400, 92, 22);

        uage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        uage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uageActionPerformed(evt);
            }
        });
        uage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uageKeyReleased(evt);
            }
        });
        jPanel2.add(uage);
        uage.setBounds(270, 350, 220, 30);

        iname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(iname);
        iname.setBounds(560, 60, 206, 22);

        icontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        icontact.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(icontact);
        icontact.setBounds(610, 400, 166, 22);

        uaddress.setColumns(20);
        uaddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        uaddress.setRows(5);
        jScrollPane3.setViewportView(uaddress);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(270, 170, 226, 90);

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(690, 490, 73, 35);

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update);
        update.setBounds(240, 490, 89, 35);

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(350, 490, 87, 35);

        display.setBackground(new java.awt.Color(204, 204, 204));
        display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        display.setText("DISPLAY");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        jPanel2.add(display);
        display.setBounds(120, 490, 95, 35);

        ucontact.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ucontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucontactActionPerformed(evt);
            }
        });
        ucontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ucontactKeyReleased(evt);
            }
        });
        jPanel2.add(ucontact);
        ucontact.setBounds(270, 400, 220, 30);

        iage1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iage1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(iage1);
        iage1.setBounds(590, 350, 160, 22);

        client_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        client_id.setForeground(new java.awt.Color(255, 255, 255));
        client_id.setText("CLIENT ID :");
        jPanel2.add(client_id);
        client_id.setBounds(150, 10, 96, 20);

        uclientid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uclientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uclientidActionPerformed(evt);
            }
        });
        uclientid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uclientidKeyReleased(evt);
            }
        });
        jPanel2.add(uclientid);
        uclientid.setBounds(270, 10, 220, 30);

        client1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        client1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(client1);
        client1.setBounds(540, 10, 224, 22);

        search.setBackground(new java.awt.Color(204, 204, 204));
        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search);
        search.setBounds(460, 490, 91, 35);

        bldgrp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bldgrp.setForeground(new java.awt.Color(255, 255, 255));
        bldgrp.setText("Blood Group :");
        jPanel2.add(bldgrp);
        bldgrp.setBounds(110, 450, 96, 30);

        ubldgrps.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ubldgrps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        ubldgrps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubldgrps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubldgrpsActionPerformed(evt);
            }
        });
        jPanel2.add(ubldgrps);
        ubldgrps.setBounds(270, 450, 220, 30);

        adhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharActionPerformed(evt);
            }
        });
        adhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adharKeyReleased(evt);
            }
        });
        jPanel2.add(adhar);
        adhar.setBounds(270, 300, 220, 30);

        weight1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        weight1.setForeground(new java.awt.Color(255, 255, 255));
        weight1.setText("Addhar Card No.        :");
        jPanel2.add(weight1);
        weight1.setBounds(80, 300, 153, 22);

        iadhar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iadhar.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(iadhar);
        iadhar.setBounds(550, 300, 200, 22);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(Adhar No Should Be In Form :XXXX XXXX XXXX)");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 330, 310, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("(Client Id must be start with 2)");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 40, 190, 14);

        lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setText("LAST NAME :");
        jPanel2.add(lname);
        lname.setBounds(130, 110, 140, 30);

        ulast_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ulast_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulast_nameActionPerformed(evt);
            }
        });
        ulast_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ulast_nameKeyReleased(evt);
            }
        });
        jPanel2.add(ulast_name);
        ulast_name.setBounds(270, 110, 220, 30);

        iname2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iname2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(iname2);
        iname2.setBounds(570, 120, 180, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandregister/140508100350_1_540x360.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-6, -6, 820, 640);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 810, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void reset()
    {
        uclientid.setEnabled(true);
        uname.setEnabled(true);
        ulast_name.setEnabled(true);
        uaddress.setEnabled(true);
        uage.setEnabled(true);
        ucontact.setEnabled(true);
        ucontact.setEnabled(true);
        ubldgrps.setSelectedIndex(0);
        adhar.setEnabled(true);
        uclientid.setText("");
        uname.setText("");
        ulast_name.setText("");
        uaddress.setText("");
        uage.setText("");
        ucontact.setText("");
        ucontact.setText("");
        ubldgrps.setSelectedIndex(0);
        adhar.setText("");
        register.setEnabled(true);
        search. setEnabled(true);
        display. setEnabled(true);
        update. setEnabled(false);
        delete. setEnabled(false);
    }
    private void ucontactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ucontactKeyReleased
        // TODO add your handling code here:
        String pattern="^[0-9]{10}$";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(ucontact.getText());
        if(!match.matches())
        {
            icontact.setText("Enter Valid Contact No");
            update.setEnabled(false);
        register.setEnabled(false);
        }
        else
        {
            icontact.setText(null);
             update.setEnabled(true);   
            register.setEnabled(true);
        }
        
    }//GEN-LAST:event_ucontactKeyReleased

    private void ucontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ucontactActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        register.setEnabled(false);
         display.setEnabled(true);
         delete.setEnabled(false);
         reset.setEnabled(false);
         try {
             Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:derby://localhost:1527/blood_bank", "omkar", "12345");
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
              
        try{
          
        String c_id=uclientid.getText();
        String name=uname.getText();
        String lname1=ulast_name.getText();
        String age=uage.getText();
        String address=uaddress.getText();
        String bld_grp=ubldgrps.getSelectedItem().toString();
       // String weight=uweight.getText();
        String contact_no=ucontact.getText();
      //  String contact_no1=ucontact1.getText();  
            String aadhar = adhar.getText();
             if(c_id.equals("")||name.equals("")||lname1.equals("")||age.equals("")||address.equals("")||bld_grp.equals("")||aadhar.equals("")||contact_no.equals(""))
            {
                this.setVisible(false);
                JOptionPane.showMessageDialog(null,"ADD ALL DATA FIELDS");
                update.setEnabled(false);
                search.setEnabled(true);
                this.setVisible(true);
                return;
                
            }
         Statement st=con.createStatement();
         
         String query="update client set aadhar_No='"+aadhar+"',firstname='"+name+"',lastname='"+lname1+"',age="+age+",address='"+address+"',contact='"+contact_no+"' where client_id="+c_id;
        // String updateContactQuery = "update contact set contact_no='"+contact_no+"' where client_id='"+client_id+"'";
    
          // modifyChPS=con.prepareStatement(updateContactQuery);
         modifyChPS=con.prepareStatement(query);
         modifyChPS.execute();
         query="update recipient set blood_group='"+bld_grp+"' where c_id="+c_id;
          modifyChPS=con.prepareStatement(query);
         modifyChPS.execute();
       
         
        
        JOptionPane.showMessageDialog(null,"Data updated");
       reset();
       
}
catch(Exception ex){
    this.setVisible(false);
JOptionPane.showMessageDialog(null,ex);
}
     
       
    }//GEN-LAST:event_updateActionPerformed
   
        
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        close();
        this.dispose();
        mainmenu mn =new mainmenu();
        mn.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void uageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uageKeyReleased
        // TODO add your handling code here:
        String pattern="^[0-9]{2}$";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(uage.getText());
        if(!match.matches())
        {
            iage1.setText("Enter Valid Age");
            update.setEnabled(false);
        register.setEnabled(false);
        }
        else
        {
            iage1.setText(null);
             update.setEnabled(true);   
            register.setEnabled(true);
        }
    }//GEN-LAST:event_uageKeyReleased

    private void uageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uageActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       reset();
    }//GEN-LAST:event_resetActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
         display.setEnabled(false);
         update.setEnabled(false);
         delete.setEnabled(false);
         reset.setEnabled(false);
         search.setEnabled(false);
         try {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/blood_bank", "omkar", "12345");
             String client_id=uclientid.getText();
             String firstname=uname.getText();
             String lastname=ulast_name.getText();
             String _age=uage.getText();
             String addr=uaddress.getText();
             String bloodgrp=ubldgrps.getSelectedItem().toString();
             String aadhar = adhar.getText();
             String contact=ucontact.getText();
             if(client_id.equals("")||firstname.equals("")||lastname.equals("")||_age.equals("")||addr.equals("")||bloodgrp.equals("")||aadhar.equals("")||contact.equals(""))
            {
                this.setVisible(false);
                JOptionPane.showMessageDialog(null,"ADD ALL DATA FIELDS");
                this.setVisible(true);
                search.setEnabled(true);
                back.setEnabled(true);
                display.setEnabled(true);
                reset.setEnabled(true);
                return;
                
                
            }
             
             String query="insert into client values("+client_id+",'"+firstname+"','"+lastname+"','"+addr+"',"+_age+",'"+contact+"','"+aadhar+"'  )" ;
             Statement st=con.createStatement();
             ResultSet r;
            st.executeUpdate(query);
            query="insert into recipient values("+client_id+",'"+bloodgrp+"')";
            st.executeUpdate(query);
            System.out.println("exec done");
             JOptionPane.showMessageDialog(null,"DATA ADDED SUCCESSFULLY");
         }
         catch(Exception ex)
        { System.out.println("not exec sql");
              JOptionPane.showMessageDialog(null,ex);
        }
        
         try {
         /*    Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:derby://localhost:1527/blood_bank", "omkar", "12345");
             System.out.println("accessed");
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        String client_id=uclientid.getText();
        String name=uname.getText();
        String lname1=ulast_name.getText();
        String age=uage.getText();
        String address=uaddress.getText();
        String contact_no=ucontact.getText();
        //String contact_no1=ucontact1.getText();
        String bld_grp=ubldgrps.getSelectedItem().toString();
          String aadhar = adhar.getText();
          System.out.println("dec done");
        try{
            
            String query="Insert into client values("+client_id+",'"+name+"','"+lname1+"','"+address+"',"+age+",'"+contact_no+"',"+aadhar+")";
            System.out.println("query1 done");
            //sta.executeUpdate("Insert into contact values('"+contact_no+"','"+client_id+"')");
            //sta.executeUpdate("Insert into contact values("+contact_no1+",'"+client_id+"')");
            //addChPS=con.prepareStatement(query);
            Statement sta=con.createStatement();
            sta.executeUpdate(query);
            System.out.println("sql1 done");
            query="Insert into recipient values("+client_id+",'"+bld_grp+"')";
            //addChPS=con.prepareStatement(query);
            sta.executeUpdate(query);
            System.out.println("sql2 done");*/
           System.out.println("window opn");
           
         //JOptionPane.showMessageDialog(null,"DATA ADDED SUCCESSFULLY");
         reset();  
         /* register.setEnabled(true);
            display.setEnabled(true);      
            search.setEnabled(true);
            back.setEnabled(true);
            System.out.println("key open");
       uclientid.setText("");
        uname.setText("");
        ulast_name.setText("");
        uaddress.setText("");
        uage.setText("");
        ucontact.setText("");
        //ucontact1.setText("");
        adhar.setText("");
        ubldgrps.setSelectedIndex(0);   
         */}catch(Exception ex){
               System.out.println("window incompleted");
              JOptionPane.showMessageDialog(null,ex);
             }
    }//GEN-LAST:event_registerActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        JOptionPane.showMessageDialog(null,"REGISTER SUCCESSFULLY !");
    }//GEN-LAST:event_registerMouseClicked

    private void unameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameKeyReleased
        String pattern="^[a-zA-Z]{3,30}$";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(uname.getText());
        if(!match.matches())
        {
            iname.setText("Enter Valid Name");
            update.setEnabled(false);
            register.setEnabled(false);
        }
        else
        {
            iname.setText(null);
            update.setEnabled(true);   
            register.setEnabled(true);
        }
        
    }//GEN-LAST:event_unameKeyReleased

    private void unameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameKeyPressed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed

    }//GEN-LAST:event_unameActionPerformed

    private void uclientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uclientidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uclientidActionPerformed

    private void uclientidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uclientidKeyReleased
        // TODO add your handling code here:
        String pattern="[0-9]+";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(uclientid.getText());
        if(!match.matches())
        {
            client1.setText("Enter Valid Client ID");
        }
        else
        {
            client1.setText(null);
        }

    }//GEN-LAST:event_uclientidKeyReleased

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        
        this.setAlwaysOnTop(false);
        /*close();
        this.dispose();
        this.setVisible(false);
        */displayrecipient clf=new displayrecipient();
        clf.setVisible(true);
        reset();
        
        
        //receipent_reg r=new receipent_reg();
        //thi.setVisible(true);
        
    }//GEN-LAST:event_displayActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if(uclientid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter client id to search");
            return;
        }
        register.setEnabled(false);
        display.setEnabled(false);
        update.setEnabled(false);
        delete.setEnabled(false);
        reset.setEnabled(false);
        
       try {
             Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:derby://localhost:1527/blood_bank", "omkar", "12345");
       }
       catch(Exception ex)
        { System.out.println("accessed denied");
              JOptionPane.showMessageDialog(null,ex);
        }
        try{
            
            Statement sta=con.createStatement();
            String query="select client_id,firstname,lastname,age,address,aadhar_no,contact,blood_group from client inner join recipient on client.client_id=recipient.c_id where client_id=?";
            searchChPS=con.prepareStatement(query);
            searchChPS.setInt(1,Integer.parseInt(uclientid.getText()));
            searchChRes=searchChPS.executeQuery();
            if(searchChRes.next())
            {
                uclientid.setText(searchChRes.getString("client_id"));
                uname.setText(searchChRes.getString("firstname"));
                ulast_name.setText(searchChRes.getString("lastname"));
                uage.setText(searchChRes.getString("age"));
                uaddress.setText(searchChRes.getString("address"));
                ucontact.setText(searchChRes.getString("contact"));
                adhar.setText(searchChRes.getString("aadhar_no"));
               ubldgrps.setSelectedItem(searchChRes.getString("blood_group"));
                search.setEnabled(false);
                delete.setEnabled(true);
                update.setEnabled(true);
               reset.setEnabled(true);
               uclientid.setEnabled(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"RECORD NOT FOUND");
                reset();
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         register.setEnabled(false);
         display.setEnabled(false);
         update.setEnabled(false);
         delete.setEnabled(false);
         reset.setEnabled(false);

        
        try{
          String query="delete from client where client_id=?";
          deleteChPS=con.prepareStatement(query);
          deleteChPS.setInt(1,Integer.parseInt(uclientid.getText()));
          deleteChPS.executeUpdate();
          query="delete from recipient where c_id=?";
          deleteChPS=con.prepareStatement(query);
          deleteChPS.setInt(1,Integer.parseInt(uclientid.getText()));
          deleteChPS.executeUpdate();
          JOptionPane.showMessageDialog(null,"Record Deleted Successfully !!");
          reset();
         // con.close(); 
        }catch(Exception ex)
        {
          JOptionPane.showMessageDialog(null, ex);
        }
         display.setEnabled(true);
            
    }//GEN-LAST:event_deleteActionPerformed

    private void ubldgrpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubldgrpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubldgrpsActionPerformed

    private void adharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adharActionPerformed

    private void adharKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adharKeyReleased
        // TODO add your handling code here:
        String pattern="^[0-9]{4}[ ][0-9]{4}[ ][0-9]{4}$";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(adhar.getText());
        if(!match.matches())
        {
            iadhar.setText("Enter Valid Adhar No");
            update.setEnabled(false);
        register.setEnabled(false);
        }
        else
        {
            iadhar.setText(null);
             update.setEnabled(true);   
            register.setEnabled(true);
        }
    }//GEN-LAST:event_adharKeyReleased

    private void ulast_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulast_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ulast_nameActionPerformed

    private void ulast_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ulast_nameKeyReleased
        String pattern="^[a-zA-Z]{3,30}$";
        Pattern patt=Pattern.compile(pattern);
        Matcher match=patt.matcher(ulast_name.getText());
        if(!match.matches())
        {
            
            iname2.setText("Enter Valid Name");
        update.setEnabled(false);
        register.setEnabled(false);
        }
        else
        {
            iname2.setText(null);
             update.setEnabled(true);   
            register.setEnabled(true);
        }
    }//GEN-LAST:event_ulast_nameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipent_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipent_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipent_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipent_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipent_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField adhar;
    private javax.swing.JLabel age;
    private javax.swing.JButton back;
    private javax.swing.JLabel bldgrp;
    private javax.swing.JLabel client1;
    private javax.swing.JLabel client_id;
    private javax.swing.JLabel contact;
    private javax.swing.JButton delete;
    private javax.swing.JButton display;
    private javax.swing.JLabel iadhar;
    private javax.swing.JLabel iage1;
    private javax.swing.JLabel icontact;
    private javax.swing.JLabel iname;
    private javax.swing.JLabel iname2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel name;
    private javax.swing.JButton register;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea uaddress;
    private javax.swing.JTextField uage;
    private javax.swing.JComboBox<String> ubldgrps;
    private javax.swing.JTextField uclientid;
    private javax.swing.JTextField ucontact;
    private javax.swing.JTextField ulast_name;
    private javax.swing.JTextField uname;
    private javax.swing.JButton update;
    private javax.swing.JLabel weight1;
    // End of variables declaration//GEN-END:variables
}
