/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
/**
 *
 * @author Akshay
 */
public class tickets extends javax.swing.JFrame {

    /**
     * Creates new form tickets
     */
    public tickets() {
        initComponents();
        t.setVisible(false);
        totalTB.setVisible(false);
                confirm.setEnabled(false);
        
    }
    public String getmax_t_id()
    {
        PreparedStatement addChPS=null, fetChPS=null, searchChPS=null, modifyChPS=null, deleteChPS=null;
    Connection con=null;
    ResultSet fetChRes=null, searchChRes=null;
    Statement st;
        
          String billNO ="";
          try {
             Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:derby://localhost:1527/railway_reservation_system", "omkar", "12345");
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
       try{
            Statement sta=con.createStatement();
            fetChRes =sta.executeQuery("select max(ticket_id) + 1 as ticketno from ticket");
            System.out.println("ticket SET");
            while (fetChRes.next()) {
               billNO  = fetChRes.getString("ticketno");
               System.out.println(billNO);
             }
               }catch(Exception ex)
        {
               JOptionPane.showMessageDialog(null,ex);
        }
          return billNO;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        idCB = new javax.swing.JComboBox();
        sour = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ticketTB = new javax.swing.JTextField();
        t = new javax.swing.JLabel();
        totalTB = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tidCB = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        book = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        seat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("RAILWAY RESERVATION SYSTEM");
        setLocation(new java.awt.Point(350, 100));
        setPreferredSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 60, 90, 28);

        idCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/railway_reservation_system","omkar","12345");
            PreparedStatement pst=conn.prepareStatement("select p_id from passenger");
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                idCB.addItem(rs.getString(1));
            }
            conn.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        idCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCBActionPerformed(evt);
            }
        });
        getContentPane().add(idCB);
        idCB.setBounds(206, 61, 98, 30);

        sour.setEditable(false);
        sour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourActionPerformed(evt);
            }
        });
        sour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sourKeyPressed(evt);
            }
        });
        getContentPane().add(sour);
        sour.setBounds(210, 240, 110, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Destination");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 280, 100, 24);

        dest.setEditable(false);
        dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destActionPerformed(evt);
            }
        });
        dest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                destKeyPressed(evt);
            }
        });
        getContentPane().add(dest);
        dest.setBounds(210, 280, 110, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. of seats");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 380, 100, 22);

        ticketTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketTBActionPerformed(evt);
            }
        });
        ticketTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ticketTBKeyPressed(evt);
            }
        });
        getContentPane().add(ticketTB);
        ticketTB.setBounds(210, 370, 50, 30);

        t.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        t.setForeground(new java.awt.Color(255, 255, 255));
        t.setText("Total");
        getContentPane().add(t);
        t.setBounds(120, 410, 44, 26);

        totalTB.setEditable(false);
        totalTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTBActionPerformed(evt);
            }
        });
        totalTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalTBKeyPressed(evt);
            }
        });
        getContentPane().add(totalTB);
        totalTB.setBounds(210, 410, 70, 30);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Passenger Train : Rs 100");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 40, 150, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SuperFast Train : Rs 200");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 60, 140, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Special Train : Rs 250");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 80, 130, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Luxury Train : Rs 1000");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 100, 130, 14);

        jLabel16.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ticket Price per Seats");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 10, 150, 16);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akshay\\Pictures\\a.jpg")); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(0, 0, 150, 140);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(330, 190, 150, 140);

        type.setEditable(false);
        type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                typeKeyPressed(evt);
            }
        });
        getContentPane().add(type);
        type.setBounds(210, 200, 110, 30);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("TICKET BOOKING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 410, 49);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("User Name ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(100, 110, 100, 30);

        pname.setEditable(false);
        getContentPane().add(pname);
        pname.setBounds(210, 110, 120, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Train No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 160, 90, 21);

        tidCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/railway_reservation_system","omkar","12345");
            PreparedStatement pst=conn.prepareStatement("select t_id from train");
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                tidCB.addItem(rs.getString(1));
            }
            conn.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        tidCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tidCBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tidCBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tidCBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tidCBMousePressed(evt);
            }
        });
        tidCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidCBActionPerformed(evt);
            }
        });
        getContentPane().add(tidCB);
        tidCB.setBounds(210, 150, 98, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TYPE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 200, 80, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Source ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 240, 69, 22);

        confirm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        confirm.setText("BOOK TICKET");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(40, 460, 120, 30);

        book.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        book.setText("CALCULATE");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        getContentPane().add(book);
        book.setBounds(210, 460, 110, 30);

        back.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back.setText("<<BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(360, 460, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<HTML><U><B>TRAIN DETAILS</B></U><HTML>");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 120, 130, 19);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Available Seats");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(80, 330, 120, 30);

        seat.setEditable(false);
        getContentPane().add(seat);
        seat.setBounds(210, 330, 50, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akshay\\Pictures\\ticketTrain.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 550, 520);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("<HTML><U><B>CHECK USER ID</B></U><HTML>");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 70, 130, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        Object idItem = idCB.getSelectedItem();
       Object tidItem = tidCB.getSelectedItem();
        
        int price = 0;
        String qtys = ticketTB.getText();
        
         if(tidCB.getSelectedIndex()==0 || idCB.getSelectedIndex()==0)
            {
                JOptionPane.showMessageDialog(this,"Select a value","Error",JOptionPane.WARNING_MESSAGE);
            }
            else if(qtys.isEmpty()== true)
            {
                JOptionPane.showMessageDialog(this,"Enter a value","Error",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
      
        pid = Integer.parseInt(idItem.toString());
       tid = Integer.parseInt(tidItem.toString());
           
                qty = Integer.parseInt(qtys);
                
                if(type.getText().equals("PASSENGER"))
                {
                    price = 100;
                    
                }
                else if(type.getText().equals("SUPERFAST"))
                {
                    price = 200;
                }
                else if(type.getText().equals("SPECIAL"))
                {
                    price = 250;
                }
                else if(type.getText().equals("LUXURY"))
                {
                    price = 1000;
                }
                 try{                    
                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                    Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/railway_reservation_system", "omkar", "12345");
                  
                    Statement stmt =conn.createStatement();
                String id1="select total_no_of_seat from train where t_id ="+tid+"";
                ResultSet rs2;
                rs2 = stmt.executeQuery(id1);
                    if(rs2.next())
                    {
                        available = rs2.getInt("total_no_of_seat");                       
                    }
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                 
                  if(qty>available)
        {
            JOptionPane.showMessageDialog(this,"Seats are not available","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
                  {
                   total = price * qty;
                totalTB.setText(" "+total);
                
                 t.setVisible(true);
        totalTB.setVisible(true);
         confirm.setEnabled(true); 
                  }
            }
    }//GEN-LAST:event_bookActionPerformed

    private void tidCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidCBActionPerformed
        // TODO add your handling code here:

         Object idItem = tidCB.getSelectedItem();
        
         try
            {
                      String USERNAME="omkar";
            String PASSWORD="12345";
            String CONN_STRING="jdbc:derby://localhost:1527/railway_reservation_system";
                
               int tidi = Integer.parseInt(idItem.toString());
                Connection conn=null;
                conn=DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
                System.out.println("Sucessful connection2");
                Statement stmt =conn.createStatement();
                String id1="select t_type,source,destination,total_no_of_seat from train where t_id="+tidi+"";
                ResultSet rs;
                rs = stmt.executeQuery(id1);
             while(rs.next())
             {
                type.setText(rs.getString("t_type"));
                sour.setText(rs.getString("source"));
                 dest.setText(rs.getString("destination"));
                 seat.setText(rs.getString("total_no_of_seat"));
            }
            }
            catch(HeadlessException | NumberFormatException  | SQLException e)
            {
                 JOptionPane.showMessageDialog(this,"Enter Correct ID!","Alert",JOptionPane.WARNING_MESSAGE);
                return;
            }
        
        
    }//GEN-LAST:event_tidCBActionPerformed

    private void totalTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTBActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:         
        Calendar cal = Calendar.getInstance();         
        SimpleDateFormat curdate = new SimpleDateFormat("yyyy-MM-dd");
        String date = curdate.format(cal.getTime());
        String trainid=tidCB.getSelectedItem().toString();
        String tid = getmax_t_id();
        System.out.println("tid:"+tid);
        int t_id=Integer.parseInt(tid);
      
        try{
                    //String ticket = tid.toString();
                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                    Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/railway_reservation_system", "omkar", "12345");
                 
                     
                    Statement st2 = conn.createStatement();                    
                    st2.executeUpdate("insert into ticket(ticket_id,Date,no_of_Seat,p_id,train_id) values("+tid+",'"+date+"',"+qty+","+pid+","+trainid+")",Statement.RETURN_GENERATED_KEYS);
                    
                  /* ResultSet r = st2.getGeneratedKeys();
                    if(r.next())
                    {
                        ticket_id = r.getInt(1);
                    }*/
                    conn.close();
                    JOptionPane.showMessageDialog(this,"Ticket booked Succesfully.","Success",JOptionPane.PLAIN_MESSAGE);
                 
                    this.setVisible(false);
                  new DispTicket(total,t_id).setVisible(true); 
            }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_confirmActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Dispid().setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new TDisp().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void sourKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sourKeyPressed
        // TODO add your handling code here:
       sour.setEditable(false);

    }//GEN-LAST:event_sourKeyPressed

    private void destKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destKeyPressed
        // TODO add your handling code here:
     dest.setEditable(false);
    }//GEN-LAST:event_destKeyPressed

    private void typeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeKeyPressed
        // TODO add your handling code here:
        type.setEditable(false);
    }//GEN-LAST:event_typeKeyPressed

    private void destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destActionPerformed

    private void ticketTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketTBActionPerformed

    private void tidCBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidCBMouseEntered
// TODO add your handling code here:
       
    }//GEN-LAST:event_tidCBMouseEntered

    private void tidCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidCBMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tidCBMouseClicked

    private void tidCBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidCBMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tidCBMousePressed

    private void tidCBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidCBMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tidCBMouseExited

    private void idCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCBActionPerformed
// TODO add your handling code here:
        
         Object idItem = idCB.getSelectedItem();
        
         try
            {
                      String USERNAME="omkar";
            String PASSWORD="12345";
            String CONN_STRING="jdbc:derby://localhost:1527/railway_reservation_system";
                
               int idi = Integer.parseInt(idItem.toString());
                Connection conn=null;
                conn=DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
                System.out.println("Sucessful connection");
                Statement stmt =conn.createStatement();
                String id1="select p_name from passenger where p_id="+idi+"";
                ResultSet rs;
                rs = stmt.executeQuery(id1);
             while(rs.next())
             {
                pname.setText(rs.getString("p_name"));
            }
            }
            catch(HeadlessException | NumberFormatException  | SQLException e)
            {
               //
                 JOptionPane.showMessageDialog(this,"Enter Correct ID!","Alert",JOptionPane.WARNING_MESSAGE);
                return;
            }
        
    }//GEN-LAST:event_idCBActionPerformed

    private void totalTBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalTBKeyPressed
        // TODO add your handling code here:
         totalTB.setEditable(false);
    }//GEN-LAST:event_totalTBKeyPressed

    private void ticketTBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticketTBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketTBKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton book;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField dest;
    private javax.swing.JComboBox idCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField seat;
    private javax.swing.JTextField sour;
    private javax.swing.JLabel t;
    private javax.swing.JTextField ticketTB;
    private javax.swing.JComboBox tidCB;
    private javax.swing.JTextField totalTB;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
private int ti;
private int nm;
private int mid;
private int total,t_id;
private int qty;
private int available;
private int tid,pid,p_id;

}


